default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DATABASE_NAME'] %>
  username: <%= ENV['DEVELOPMENT_DATABASE_USERNAME'] || ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['DEVELOPMENT_DATABASE_PASSWORD'] || ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE_NAME'] %>
  username: <%= ENV['TEST_DATABASE_USERNAME'] || ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['TEST_DATABASE_PASSWORD'] || ENV['POSTGRES_PASSWORD'] %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>
    username: <%= ENV["PRODUCTION_DATABASE_USERNAME"] %>
    password: <%= ENV["PRODUCTION_DATABASE_PASSWORD"] %>
    url: <%= ENV['PRODUCTION_DATABASE_URL'] %>

  cable:
    <<: *default
    database: <%= ENV['PRODUCTION_CABLE_DATABASE_NAME'] || "#{ENV['PRODUCTION_DATABASE_NAME']}_cable" %>
    username: <%= ENV['PRODUCTION_CABLE_DATABASE_USERNAME'] || ENV['POSTGRES_USERNAME'] %>
    password: <%= ENV['PRODUCTION_CABLE_DATABASE_PASSWORD'] || ENV['POSTGRES_PASSWORD'] %>
